repos:
  # Code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0          # version of black to use
    hooks:
      - id: black
        args: [--line-length=100]

  # Linter / autofixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8          # version of ruff to use
    hooks:
      - id: ruff
        args: [--fix]

  # Type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1         # version of mypy to use
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: []
