[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
lint.select = ["E","F","I","B","UP"]
lint.ignore = []

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true